---
- name: Fill motd file with host data
  hosts: node1
  become: true
  tasks:
  - template:
      src: templates/motd-facts.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0664
