---
- name: Output facts within a playbook
  hosts: localhost
  tasks:
  - name: Print Ansible facts
    debug:
      msg: The Default IPV4 address of {{ ansible_fqdn }} is {{ ansible_default_ipv4.address }}
